In [ ]:
import pandas as pd

df1 = pd.DataFrame(
    {"acc": [13, 21, 33, 48], "name": ["Ram", "Shyam", "Hari", "Krishna"], "age" : [21, 65, 34, 88]} 
)

df2 = pd.DataFrame(
    {"acc": [13, 21, 33, 48], "principle": [500, 658, 4032, 500], "interest" : [6.3, 4.25, 9.8, 5.6]} 
)

In [ ]:
df1, df2

(   acc     name  age
 0   13      Ram   21
 1   21    Shyam   65
 2   33     Hari   34
 3   48  Krishna   88,
    acc  principle  interest
 0   13        500      6.30
 1   21        658      4.25
 2   33       4032      9.80
 3   48        500      5.60)

# Concatenation

In [ ]:
pd.concat([df1, df2], axis = 1)

   acc     name  age  acc  principle  interest
0   13      Ram   21   13        500      6.30
1   21    Shyam   65   21        658      4.25
2   33     Hari   34   33       4032      9.80
3   48  Krishna   88   48        500      5.60

In [ ]:
pd.concat([df1, df2], axis = 0, ignore_index = True)

   acc     name   age  principle  interest
0   13      Ram  21.0        NaN       NaN
1   21    Shyam  65.0        NaN       NaN
2   33     Hari  34.0        NaN       NaN
3   48  Krishna  88.0        NaN       NaN
4   13      NaN   NaN      500.0      6.30
5   21      NaN   NaN      658.0      4.25
6   33      NaN   NaN     4032.0      9.80
7   48      NaN   NaN      500.0      5.60

# Merging

In [ ]:
import pandas as pd

df1 = pd.DataFrame(
    {"key": ["AB", "CB", "AC", "DE"], "name": ["Ram", "Shyam", "Hari", "Krishna"], "age" : [21, 65, 34, 88]} 
)

df2 = pd.DataFrame(
    {"key": ["AB", "CC", "AC", "DF"], "principle": [500, 658, 4032, 500], "interest" : [6.3, 4.25, 9.8, 5.6]} 
)

In [ ]:
df1, df2

(  key     name  age
 0  AB      Ram   21
 1  CB    Shyam   65
 2  AC     Hari   34
 3  DE  Krishna   88,
   key  principle  interest
 0  AB        500      6.30
 1  CC        658      4.25
 2  AC       4032      9.80
 3  DF        500      5.60)

In [ ]:
pd.merge(df1, df2, how = "inner", on = "key")

  key  name  age  principle  interest
0  AB   Ram   21        500       6.3
1  AC  Hari   34       4032       9.8

In [ ]:
pd.merge(df1, df2, how = "right", on = "key")

  key  name   age  principle  interest
0  AB   Ram  21.0        500      6.30
1  CC   NaN   NaN        658      4.25
2  AC  Hari  34.0       4032      9.80
3  DF   NaN   NaN        500      5.60

In [2]:
import pandas as pd

df1 = pd.DataFrame(
    {"key": ["AB", "CB", "AC", "DE"], "name": ["Ram", "Shyam", "Hari", "Krishna"], "age" : [21, 65, 34, 88]} 
)

df2 = pd.DataFrame(
    {"key": ["AB", "CC", "AC", "DF"], "principle": [500, 658, 4032, 500], "age" : [6.3, 4.25, 9.8, 5.6]} 
)

In [3]:
df1, df2

(  key     name  age
 0  AB      Ram   21
 1  CB    Shyam   65
 2  AC     Hari   34
 3  DE  Krishna   88,
   key  principle   age
 0  AB        500  6.30
 1  CC        658  4.25
 2  AC       4032  9.80
 3  DF        500  5.60)

In [4]:
pd.merge(df1, df2, how = "inner", on = "key")

  key  name  age_x  principle  age_y
0  AB   Ram     21        500    6.3
1  AC  Hari     34       4032    9.8

In [5]:
pd.merge(df1, df2, how = "inner", on = "key", suffixes = ("_df1", "_df2"))

  key  name  age_df1  principle  age_df2
0  AB   Ram       21        500      6.3
1  AC  Hari       34       4032      9.8

In [6]:
# Alternative syntax

df1.merge(df2, on = "key", how = "inner")

  key  name  age_x  principle  age_y
0  AB   Ram     21        500    6.3
1  AC  Hari     34       4032    9.8

# Joining

In [ ]:
df1

  key     name  age
0  AB      Ram   21
1  CB    Shyam   65
2  AC     Hari   34
3  DE  Krishna   88

In [8]:
df2

  key  principle   age
0  AB        500  6.30
1  CC        658  4.25
2  AC       4032  9.80
3  DF        500  5.60

In [9]:
df1.join(df2, how = "inner", lsuffix = "_left", rsuffix = "_right")

  key_left     name  age_left key_right  principle  age_right
0       AB      Ram        21        AB        500       6.30
1       CB    Shyam        65        CC        658       4.25
2       AC     Hari        34        AC       4032       9.80
3       DE  Krishna        88        DF        500       5.60

In [10]:
df1.set_index("key", inplace = True )
df1

        name  age
key
AB       Ram   21
CB     Shyam   65
AC      Hari   34
DE   Krishna   88

In [11]:
df2.set_index("key", inplace = True )
df2

     principle   age
key
AB         500  6.30
CC         658  4.25
AC        4032  9.80
DF         500  5.60

In [14]:
df1.join(df2, how = "inner", lsuffix = "_left", rsuffix = "_right")

     name  age_left  principle  age_right
key
AB    Ram        21        500        6.3
AC   Hari        34       4032        9.8