In [6]:
import sklearn

import pandas as pd

sklearn.show_versions()

System:
    python: 3.14.1 (v3.14.1:57e0d177c26, Dec  2 2025, 08:45:31) [Clang 16.0.0 (clang-1600.0.26.6)]
executable: /Users/pramishsubedi/DSML/.venv/bin/python
   machine: macOS-26.6.2-arm64-arm-64bit-Mach-O

Python dependencies:
      sklearn: 1.9.0
          pip: 26.2.1
   setuptools: None
        numpy: 2.5.2
        scipy: 1.18.1
       Cython: None
       pandas: 3.0.5
   matplotlib: 3.11.1
       joblib: 1.6.0
threadpoolctl: 3.6.0
     narwhals: 2.25.0

Built with OpenMP: True

threadpoolctl info:
       user_api: openmp
   internal_api: openmp
    num_threads: 10
         prefix: libomp
       filepath: /Users/pramishsubedi/DSML/.venv/lib/python3.14/site-packages/sklearn/.dylibs/libomp.dylib
        version: None

In [4]:
titanic_df = pd.read_csv("titanic/train.csv")

titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
### Nominal Data  -> data without natural order
titanic_df.Sex

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: str

# One- Hot Encoding

In [8]:
# Pandas
pd.get_dummies(titanic_df, columns=["Sex","Embarked"], dtype=int).head(5)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,0,1,0,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,1,0,1,0,0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,1,0,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,1,0,0,0,1
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,0,1,0,0,1

In [10]:
from sklearn.preprocessing import OneHotEncoder

one_hot_encoder = OneHotEncoder(sparse_output = False)

In [ ]:
one_hot_encoder.fit_transform(
    titanic_df[["Sex", "Embarked"]]
)

array([[0., 1., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       ...,
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.]], shape=(891, 6))

In [13]:
one_hot_encoder.categories_

[array(['female', 'male'], dtype=object),
 array(['C', 'Q', 'S', nan], dtype=object)]

In [14]:
### Ordinal Data  -> data with natural order

titanic_df.Embarked

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: str

In [20]:
# Pandas

#titanic_df["Encoded_Embarked"], rule = titanic_df.Embarked.factorize(sort = True)

titanic_df["Encoded_Embarked"], rule = pd.factorize(titanic_df.Embarked)

In [21]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Encoded_Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

In [22]:
rule

Index(['S', 'C', 'Q'], dtype='str')

In [26]:
titanic_df.Encoded_Embarked.value_counts()

Encoded_Embarked
 0    644
 1    168
 2     77
-1      2
Name: count, dtype: int64

In [27]:
titanic_df['Embarked'].isnull().sum()

np.int64(2)

In [29]:
titanic_df['Embarked'][titanic_df['Embarked'].isna()]

61     NaN
829    NaN
Name: Embarked, dtype: str

In [30]:
final_df = titanic_df.drop(
    ["Name", "PassengerId", "Ticket", "Encoded_Embarked" ], axis = 1
)

In [32]:
final_df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S